### ISSUE TITLE
version independent call

### ISSUE THREAD

**Issue by olesenm** [timofeymukha/openfoam_ci#1]
https://github.com/timofeymukha/openfoam_ci/blob/c11aaf7fe3e48fcfe9e41f7584b0bfbde72745b6/.cirrus.yml#L5

I saw this. Currently updating images to have a /usr/bin/openfoam soft-link. So in the near future (eg, later today) should be able to replace with

```
container:
  image: opencfd/openfoam-dev:latest
test_script:
  - /usr/bin/openfoam wmake
```

Similarly will update the other images too. Eg,
```
container:
  image: opencfd/openfoam-dev:2206
test_script:
  - /usr/bin/openfoam wmake
```

This should make things a fair bit easier to maintain for you.

**Comment by timofeymukha** [comment]
Perfect, thanks for the heads-up, Mark!

**Comment by timofeymukha** [comment]
Adjusted the config.

**Comment by olesenm** [comment]
Definitely looks prettier like that.
